default_platform(:ios)

platform :ios do
  desc "Run unit test"
  lane :build do
    build_app(
      scheme: "SwiftyFirestore",
      skip_package_ipa: true
    )
  end

  lane :test do
    run_tests(
      scheme: "SwiftyFirestore"
    )
  end
end
